name: Ripsecrets Check

on:
  pull_request:
    types:
      - opened

jobs:
  ripsecrets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: sirwart/ripsecrets-action@v0.1.0
